module.exports = {
    sessionData : [
        {
            name: 'Raveesh Agarwal',
            session: 'Guide to State Management For Flutter, Android, PWAs etc',
            speakerDetails: 'Managing Director at Cookytech',
            speakerAbout: 'Entrepreneur, software craftsman and technology enthusiast. Building teams, experiences and businesses for years.',
            sessionAbout: `State Management is a hot topic of debate in multiple technical circles. Developers can not even find a common ground to agree on what "state" really is. The answer to "how to manage state" should not end with "learn how to use package X". State management is a fundamental skill that all software engineers should hone. Through this session, I want to invoke a much-needed discussion on State Management.`,
            profilePic: 'https://sessionize.com/image?f=1e9b76395e07392e4ed63d4dc17885dd,200,200,True,False,41-6694-4472-a7a2-b5771f06f477.e5a71ea7-fac3-4c33-abed-2db4257b6274.jpg',
        },
        {
            name: 'Richard Süselbeck',
            session: 'Where the Heck Am I? Understanding Location in Your Application',
            speakerDetails: 'Principal Developer Evangelist for HERE Technologies',
            speakerAbout: `Richard Süselbeck is a Principal Developer Evangelist for HERE Technologies, the world's leading location technology company. With over a decade of experience in teaching and training developers, he travels the globe to help them build the world of tomorrow using the HERE Location APIs. Richard has a PhD in Information Systems and lives in Berlin with his wife and no dogs.`,
            sessionAbout: `
            Using GPS to find out exactly where we are is one of the more awesome powers of our mobile devices. It also poses some of the toughest challenges to developers, who must prevent excessive battery drain and deal with insufficient accuracy. In this talk we will learn how to face these challenges`,
            profilePic: 'https://sessionize.com/image?f=33637af63eedf7bf6e48a70cb4b5873b,200,200,True,False,09-a9c9-4769-a25c-188e3d091e34.0655608e-d126-435a-9083-c03fa1f15f8b.jpg',
        },
        {
            name: 'Bapusaheb Patil',
            session: 'CameraX: Make photography easier on Android!',
            speakerDetails: 'Mobile Engineer at Softway',
            speakerAbout: `I mentor people on e-learning platforms for Android and UX Design. I make apps, watchfaces & memes. Not necessarily in that order. I love Android and Flutter, but sometimes they don't love me back.  occasionally blog about AR food on my Instagram. Please check it out, I promise you, you won't regret it because it's not that funny`,
            sessionAbout: `In this session, I'll talk about the new CameraX library in Jetpack by Google. CameraX makes implementing features like image preview, image analysis and image capturing easier. It also helps us leverage additional and in-demand features like Portrait, HDR, Night mode, and more.`,
            profilePic: 'https://sessionize.com/image?f=29a5fb339cd48bc50c0a7d5eb9b90a40,200,200,True,False,f19e8e8c-4232-4770-96cf-b484ad3fc992.jpg',
        },
        {
            name: 'Ana Baotić',
            session: 'Inhibiting the impostor',
            speakerDetails: 'Asseco SEE, PM',
            speakerAbout: 'Ana is a software engineer with over 7 years of experience in Android. During college, she focused on various e-learning projects and plagiarism detection. After getting her Masters degree in CS, she started developing for Android, working on various projects in the telecommunication, medical and travel industry. After switching to mobile banking and security, in 2016 she took the role of Technical Manager of Mobile Banking. She is currently working as a PM at Asseco SEE',
            sessionAbout: `In this talk we will go over the basic steps that will help you materialise, deconstruct and take control of that voice, helping you distinguish the useful bits of information that can help you grow from the overwhelming debris and clutter. You will learn how to notice the early signs of its onset and manage the situation to your benefit. Finally, you will learn to use simple tools that will help you recognise and acknowledge your achievements and help yourself and others fight the invisible menace.`,
            profilePic: 'https://sessionize.com/image?f=96d5d562ed40cf01ac5b198d95dfaafa,200,200,True,False,15-0e0d-4318-97a7-e11570176324.131586f6-94de-44e4-affc-908040cf7939.jpg',
        },
        {
            name: 'Paya Do',
            session: 'Accessibility for Design System',
            speakerDetails: 'Research in Design, Mercari, Inc.',
            speakerAbout: 'I was born in Vietnam, educated and have worked in Singapore, the US and Japan. I design and code if needed. My professional career is mostly in Japan as a designer. I produced and designed some popular social game titles in Japan, also helped develop and design Amazon, Diesel, Marc Jacobs, Diesel and Ray-Ban e-commerce interface and system for Japanese market (still currently in-use)',
            sessionAbout: `In our current economic landscape, more people are having access to smartphones and the internet. People with temporary & permanent disabilities are often neglected when we design and develop product, often in Asia & also Vietnam. When we stop using our abilities as a baseline, we can provide an inclusive product/service that reflects the real world and the diverse human.`,
            profilePic: 'https://sessionize.com/image?f=e3141907670c3c69fb92ee25e884953e,200,200,True,False,6e-c43f-45e3-95bb-ae2696f9d95e.7eb5e0a0-ed38-4f06-9a2f-078e506b18d9.jpg',
        },
        {
            name: 'Anamika Tripathi',
            session: 'Deep dive into Constraint Layout',
            speakerDetails: 'Android Developer at Zomato',
            speakerAbout: `Anamika Tripathi is an Android developer who loves to explore Android features. She is also an open-source enthusiast & has been Google summer of Code’18 student & GSoC’19 Mentor too. Currently, She is working at Zomato as an Android Engineer. She has also contributed to articles at mindorks.com. Apart from coding, She loves reading books, hanging out with family & exploring how the human mind works!`,
            sessionAbout: `In this talk, we will cover best practices of using ConstraintLayout on Android, particularly on Constraint layout 2.0 library. It will cover the topics from the getting started, helper objects and how MotionLayout differs from the framework of the existing animation. It will also cover tips & tricks to use the layout editor.`,
            profilePic: 'https://sessionize.com/image?f=6c1931c952217fd1b1134b32c67e7c44,200,200,True,False,7a-34f5-4cf7-a9a3-72622c2afb22.6f80fd8e-6cb5-47fc-b381-c9949bbed382.jpg',
        },
        {
            name: 'Enrique Lopez Mañas',
            session: 'Kotlin/Native for Mobile Devs and other stories',
            speakerDetails: 'Google Developer Expert',
            speakerAbout: `Enrique López Mañas is a Google Developer Expert and independent IT consultant. He has been working with mobile technologies and learning from them since 2007. He is an avid contributor to the open source community and a FLOSS (Free Libre Open Source Software) kind of guy, being among the top 10 open source Java contributors in Germany. He is a part of the Google LaunchPad accelerator, where he participates in Google global initiatives to influence hundreds of the best startups from all around the globe. He is also a big data and machine learning aficionado.`,
            sessionAbout: `You have been hearing about Kotlin/Native for a while, and aren't you yet sure about how to use it? Can you really use it to write multiplatform components? What about the web, and your backend? Join us in this excursion in the Kotlin/Native world, where you will learn about its advantages, disadvantages, state-of-the-art, and whether you can use it to develop your mobile applications properly.`,
            profilePic: 'https://sessionize.com/image?f=45f06f55450db5cd0e212980513befec,200,200,True,False,34285f3a-76cf-4459-960a-a960e4ccd67a.jpg',
        },
        {
            name: 'Soham Mondal',
            session: 'Designing offline first apps for India',
            speakerDetails: 'Founder at Triveous, Google Developer Expert for User Experience',
            speakerAbout: `Soham is the founder of Triveous, a startup based out of Bangalore, India and he has created the Audio Recording platform "Skyro"`,
            sessionAbout: `In this talk I will talk about how to best design offline first apps for India. I have talked about something similar in my earlier talk at Google Developer Days India, 2017. Since 2017, I have worked on various, large scale, offline first apps and I want to showcase some of the learnings here`,
            profilePic: 'https://sessionize.com/image?f=5a1f9de8eedaac621e0d17b73479a140,200,200,True,False,8c2a7aa7-cc22-4041-9b95-08fe19e5c78b.jpg',
        },
        {
            name: 'Pooja Bhaumik',
            session: 'Migrating a 1M users production app into Flutter',
            speakerDetails: 'Google Developer Expert - Flutter',
            speakerAbout: `Pooja Bhaumik is the first woman Google Developer Expert for Flutter in India. Currently working in Bounce in Bangalore, she is an early Flutter adopter and a respected community member who loves to share her insights through technical blog posts, public speaking and open source contributions. Co-founder of WomenDroid and xxCode communities, she is also passionate about diversity and inclusion and aims to bring a change in the gender ratio in technology.`,
            sessionAbout: `In this session, I talk about how we migrated the Bounce app from two native Android and iOS codebases to one codebase that serves to Android, iOS and the Web and the challenges we had to face in terms of the migration of two huge native codebases into Flutter. Further, I will discuss about the architecture we adopted, performance differences, help from the community, and implementing a workaround for the non-supported features in Flutter. `,
            profilePic: 'https://sessionize.com/image?f=5acb773bc89f93488f8a52c76fc512fe,200,200,True,False,5d-9811-404c-befd-df22f8c48f9f.69087e03-c30b-4941-ab6d-605fdba39af7.jpg',
        },
        {
            name: 'Bedanta Bikash Borah',
            session: "Let's Stream that Video - an ExoPlayer Starters Guide",
            speakerDetails: "Android Engineer at Byju's.",
            speakerAbout: `Android Developer with a good design sense. Deep Learning enthusiast. Marvel, DC fan. Loves CS:GO.`,
            sessionAbout: `Have you ever thought how much work it is to build a streaming video player as robust as YouTube? Have you ever wondered how to play a video with subtitle and multiple audio tracks like Netflix? How does YouTube do streaming which adapts the video quality based on your network speed?`,
            profilePic: 'https://sessionize.com/image?f=0426f9e2360614a472482ddc0a73005b,200,200,True,False,b9-c572-4e25-b1bc-c20ee829a68a.af59f193-e72d-4093-902c-dc3ad57ecbde.jpg',
        },
        {
            name: 'Rounak Bose',
            session: "A UX primer for lone-app developers",
            speakerDetails: "Creative Director, Cookytech",
            speakerAbout: `2 parts space enthusiast, 1 part truth-seeker, 3 parts designer, 1 part writer, 2 parts tech-geek and 1 part realist. Too many parts? Not for me!`,
            sessionAbout: `The experience that a User has with every part and aspect of a product or service is by far the determining factor as to whether the User would continue to be involved with that product. Most developers and designers forget these absolutely core principles of each design process and leave their users either dissatisfied, or frustrated, or worse - wondering why the app exists at all. `,
            profilePic: 'https://sessionize.com/image?f=1ea41698bcbcba8dcf554778d97a115a,200,200,True,False,1e-8123-49ea-86d8-11286c01bc18.5af3f57d-71b2-4b77-a209-088386bd7008.jpeg',
        },
        {
            name: 'Amrit Sanjeev',
            session: "TBD",
            speakerDetails: "Senior Developer Advocate - Google",
            speakerAbout: `Amrit Sanjeev works as a developer advocate in the partner developer relations team and works with partners in India. Previously he managed multiple programs like Google developer communities (GDG), Google developer expert (GDE) and developer agencies program. Prior to joining Google he worked for companies including Intuit, Philips and IBM. He was the first Android GDE from India and actively participates in developer communities in India.`,
            sessionAbout: ``,
            profilePic: 'https://sessionize.com/image?f=861b1efe8aa7b96078f38ee7ef148c64,200,200,True,False,73-d62b-4a05-a52b-9be52909a462.a73731f2-0e73-4d60-9683-15bc936ae010.jpg',
        },
        {
            name: 'Ketan Jogani',
            session: "CRED: the future we are building",
            speakerDetails: "Head of Mobile Technology @ CRED",
            speakerAbout: 'An intern, a developer, a free-lancer, a founder and a leader; with 7 years of experience in aggressively paced start-ups of the likes of OLA and CRED, most of my energy is driven through sheer enthusiasm of building consumer mobile tech at a massive scale. Along with having domain expertise, I am passionate about mentoring and building teams for scale to deliver in the most Pareto optimal way',
            sessionAbout: `“Why should the good actors always finish last?”, “How do we reward good actors in society?”: questions like these led us to make a few bold bets and create a community of credit-worthy individuals. As put across by Mr. Jobs, “Design is not just what it looks like and feels like. Design is how it works”. In a space where we are all striving to “connect the dots” design is product and product is design; what is invisible is the engineer’s work! At CRED, we are not only obsessed with our outcomes but also we are creating an ecosystem of innovation and invention.`,
            profilePic: 'https://sessionize.com/image?f=0951652fe4d7489526116f2ba2561bb1,200,200,True,False,1e-c62e-441b-85ec-03469d0bce2b.0c1f2c49-cc77-4c89-9616-4ccfa935d09e.jpg',
        },
        {
            name: 'Rivu Chakraborty',
            session: "Dive into Async apps with Kotlin Coroutines",
            speakerDetails: "Kotlin Evangelist, Author, Sr. Android Dev., Speaker, Community Person",
            speakerAbout: 'Rivu Chakraborty is a Google Certified Android Developer, Caster.io instructor, Sr. Tech Member of Institute of Engineers (India). Having total 7+ years of experience he is presently working as a Sr. Software Engineer (Android) at BYJU`S The Learning App. He has authored multiple Kotlin and Android Development books including Reactive Programming in Kotlin, Functional Kotlin, Hands-On Data Structures and Algorithms with Kotlin and Coroutines for Android Developers',
            sessionAbout: `This talk highlights the challenges underpinning some of the paradigms of asynchronous programming, in particular the callback based approach. The talk will address how Kotlin aims to solve this problem with coroutines by providing a synchronous interface to the user.`,
            profilePic: 'https://sessionize.com/image?f=98f595eebf939cec2680962f110a1fc7,200,200,True,False,7c-9ec9-4533-b50f-0b03493041d1.0bdfa3c1-b3dc-43ac-a823-925657ef776f.jpg',
        },
        {
            name: 'Brijesh Masrani',
            session: "Let's Stream that Video - an ExoPlayer Starters Guide",
            speakerDetails: "Lead Android Engineer @ Byju's",
            speakerAbout: `Hi, My name is Brijesh. I'm a Lead Android Enginner at Byju's. I’m passionate about coding and solving problems using technology. I love to participate in Hackathon and solve the real issues apart from daily job challenges.`,
            sessionAbout: `Have you ever thought how much work it is to build a streaming video player as robust as YouTube? Have you ever wondered how to play a video with subtitle and multiple audio tracks like Netflix? How does YouTube do streaming which adapts the video quality based on your network speed?`,
            profilePic: 'https://sessionize.com/image?f=82671c0daacac4476dd9340e76cd35d5,200,200,True,False,ec-0ff0-4aef-8a74-2b9c13f29c28.3e4a9efc-1d55-4391-a85d-d175d256f7d3.jpg',
        },
        {
            name: 'Sean Smith',
            session: "Nightmare Mitigation: How to Defend Your Product With a Security Assurance Program",
            speakerDetails: "Senior Security Program Manager - Google",
            speakerAbout: `Sean has worked in application security and SDL for more than a decade. He got his start in security at Indiana University working to prevent web application attacks. He eventually moved to Microsoft where he worked on projects such as Exchange, Kinect, Xbox One and the Microsoft Threat Intelligence Center. Recently he has joined Google to manage the Android OS SDL Process.`,
            sessionAbout: `What does it mean to build a secure product? How do you ensure your product is designed securely before writing the first line of code or picking the first component? And how do you prove it to leadership and external entities such as auditors or regulators?`,
            profilePic: 'https://sessionize.com/image?f=5449e854353acbca4f18b15d1c452f15,200,200,True,False,08-5894-4b26-9e7d-6c941bc67e31.bddff4cf-6508-451a-a03d-9dff44de63f6.jpg',
        },
        {
            name: 'Darshan Pania',
            session: "Coding with your hands tied - A session on developing Android Libraries.",
            speakerDetails: "Lead Android Developer at CleverTap",
            speakerAbout: `Java/Android Developer for the past 7 years and trying to make a dent in the App universe by building a robust Android Library currently being used by 4000+ apps`,
            sessionAbout: `This session goes through the nuances on how Android libraries have to be developed in a restricted environment as they run inside other apps. This session will not be very practical in terms of development but will be more of an interactive session with the audience, where I will compare the different aspects of Android development in terms of comparison between App development and SDK development and pick their brains on how would they go about developing an Android Library if they got a chance.`,
            profilePic: 'https://sessionize.com/image?f=5f8fbd4b509c5f8634a7f32e095a1007,200,200,True,False,59744d28-cf64-4afb-ad65-0df3fece986d.jpg',
        },
        {
            name: 'Rahul Ravikumar',
            session: "WorkManager: Beyond the Basics",
            speakerDetails: "Software Engineer at Google",
            speakerAbout: `Software Engineer on the Android Toolkit team`,
            sessionAbout: `This talk explores WorkManager’s implementation in detail. It will introduce WorkManager’s schedulers; the in-process scheduler, the AlarmManager based scheduler as well as the one based on JobScheduler. This talk will also map the state machine of the Workers to the interaction between all these Schedulers and the other key abstractions in WorkManager’s implementation. Finally this talk will do a deep dive on the AlarmManager based implementation of the Scheduler and the implementation of the WorkContinuation.`,
            profilePic: 'https://sessionize.com/image?f=ad23c55904b16a464d11f0818be89692,200,200,True,False,019901dd-fc75-4fef-a9b7-cece6452c414.jpg',
        },
        {
            name: 'Faiz Malkani',
            session: "Building for a Voice First World",
            speakerDetails: "Agrahyah Technologies",
            speakerAbout: `Faiz is a Google Expert for Design, working at Agrahyah Technologies. He helps designer and developer teams build usable and accessible products, evangelizing inclusive design, accessible technology, and community building.`,
            sessionAbout: `We’re moving fast towards a world without screens, with 30% of all searches set to happen without a screen by 2020. Google's investing heavily into voice-first interfaces, making it the new touch, and most of it remains uncharted territory, since building for the ear is very different than building for the eyes.`,
            profilePic: 'https://sessionize.com/image?f=350a846b3afac9fbd821c68f497a7957,200,200,True,False,a15c8492-01ab-4ea6-90b1-3a0ded7f7735.jpg',
        },
        {
            name: 'Rohit singh',
            session: "Multi modularization scaling app",
            speakerDetails: "Android Dev works in Grab",
            speakerAbout: `Have been android developer for some years, loves to write good cleaner code. Have won award for best app of the year.`,
            sessionAbout: `Once your application codebase is big, and your team scales well. It becomes harder to add or update new features, build time increases exponentially refactoring takes a lot of time. Experimenting with a set of library becomes difficult in a monolithic app module. I aim to provide guidance from lessons learned and best practices so you don't have to go through the learning curve all on your own.`,
            profilePic: 'https://sessionize.com/image?f=e4644240eecc225df97930a91408cf9c,200,200,True,False,72-e8dd-4fd1-a789-811e3373bcb7.3c02e0f7-a7c8-47b8-8f6c-385960e1b231.jpeg',
        },
        {
            name: 'Andrii Rakhimov',
            session: "How to build a messenger for Android?",
            speakerDetails: "Lead Android Engineer",
            speakerAbout: 'Lead Android Engineer at Lalafo. More than 6 years working with mobile. Have experience of scaling apps from several thousand to millions of users. Passionate about mobile and technology as well as about giving back to the community.',
            sessionAbout: `It looks so simple outside, the app which can send messages from one user and receive from others. This is what we were thinking from start. 9 months passed we're still on it. In this talk, I will go through the main parts of the messenger project such as transport, synchronization, architecture, storage, pagination as well as explain common mistakes we've made on the way to instant messenger. `,
            profilePic: 'https://sessionize.com/image?f=8675b82085fc215400c8611f98363341,200,200,True,False,f7-51c4-4997-ba87-8b50a6a44ab4.9bc5c9a4-5244-4f0f-b2f2-15a12b57309c.jpg',
        },
        {
            name: 'Adit Lal',
            session: "Dive into Async apps with Kotlin Coroutines",
            speakerDetails: "Product Engineer at GoJek",
            speakerAbout: `Adit is a Product Engineer, Android at GoJek. He is been working in the industry for close to 6 years. Some of his hobbies are Stargazing, Travel and Landscape Photography`,
            sessionAbout: `This talk highlights the challenges underpinning some of the paradigms of asynchronous programming, in particular the callback based approach. The talk will address how Kotlin aims to solve this problem with coroutines by providing a synchronous interface to the user.`,
            profilePic: 'https://sessionize.com/image?f=0e1f94d20802f2c96896cfe1d90f23a3,200,200,True,False,18-131f-4ff0-b644-43ba706b82e8.8d1b0d00-5caa-48bb-889d-94e931646e3c.jpg',
        },
        {
            name: 'Jitin Sharma',
            session: "@Inject Basics",
            speakerDetails: "Android Engineer, Gojek",
            speakerAbout: `Jitin works as an Android Engineer at Gojek, India where he works on aligning design and development as part of UX engineering. He previously developed travel applications for various airlines and has 5 years of industry exprience. He writes about Android and Kotlin on Medium, is an open source contributor and has a certification in Android Developer Nanodegreee from Udacity.`,
            sessionAbout: `Dependency Injection is a concept which has become quite popular among Android developers as our applications break barriers on features and at the same time project complexity increases. It is also a heavily researched topic by developers with 20k questions on stack overflow(2k+ for dagger).`,
            profilePic: 'https://sessionize.com/image?f=c1ac018cf6b0a25b017d158eaf5b3186,200,200,True,False,70-c13b-4ad5-aa0a-ddb502e5eed6.e852c4c2-acb4-486a-9e57-bc69ed0c3310.jpg',
        },
        {
            name: 'Ragunath Jawahar',
            session: "Reimagining Android Productivity with TCR",
            speakerDetails: "Lead Product Engineer at Obvious",
            speakerAbout: `Ragunath Jawahar is a Lead Product Engineer working with Obvious (formerly Uncommon Bangalore), a prominent design studio that has worked with several unicorn startups in India. He specialises in mobile app architectures, refactoring and test-driven development. He has a knack for building awesome teams and believes in “you are only as good as the team you build”.`,
            sessionAbout: `What slows us down? Bad code. Code that won't compile, code that breaks the functionality, code that doesn't do what it is supposed to do. What if someone waved a magic wand and made bad code disappear in a snap? Imagine a world where everyone checks-in only good code. Now, that opens up a lot of possibilities.`,
            profilePic: 'https://sessionize.com/image?f=a32a37b6746e8c826f1077451e0452a1,200,200,True,False,27-7480-4efe-89e5-3dc7e77f977c.37a745d0-04d4-47c6-a003-c6d60212398c.jpg',
        },
        {
            name: 'Rajendran Dandapan',
            session: "Closing Keynote",
            speakerDetails: "Director Of Engineering - Zoho",
            speakerAbout: `.`,
            sessionAbout: ``,
            profilePic: 'https://sessionize.com/image?f=65aa6f581c6a2120179be76e326a3ea3,200,200,True,False,73-d62b-4a05-a52b-9be52909a462.75204308-34db-4d04-beeb-84045e9d4478.jpeg',
        },
        {
            name: 'Chetan Sachdeva',
            session: "The Anatomy of RIBs",
            speakerDetails: "Software Engineer at Uber",
            speakerAbout: `I am an Android Developer from India and want to make this world a better place by leveraging technology. I like to write clean, testable code that adheres to SOLID principles.`,
            sessionAbout: `RIBs is used across all the Android/iOS apps at Uber. It is a cross-platform architectural framework which is inspired by VIPER. This architecture has proven to scale to hundreds of engineers working on the same codebase. In this talk, we'll focus on how we can implement RIBs and write Plugins in Android.`,
            profilePic: 'https://sessionize.com/image?f=3513ef0a2791c2d079493f74b90a60dc,200,200,True,False,8e-49bb-4195-a8df-a7a22438a512.7702ef45-5397-4c3c-a5f6-504e2199dc7d.JPG',
        },
    ]
} 